In [ ]:
# Import libraries 
import numpy as np
import matplotlib.pyplot as plt

## Exercise 1 : Compute A(T).A

### Step 1 : create array

In [ ]:
import numpy as np

# creating an array of arrays (2D array)
A = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

print(A)

[[1 2 3]
 [4 5 6]]


### Step 2 : perform Transpose  

In [4]:
AT = A.T

print(AT)

[[1 4]
 [2 5]
 [3 6]]


### Step 3 : Multiply 

To multiply two matrices, the number of columns in the first matrix must match the number of rows in the second

In [5]:
ATA = AT @ A

print(ATA)

[[17 22 27]
 [22 29 36]
 [27 36 45]]


## Exercise 2 : Create a Linear function 
equation : y=2x1​+3

### Step 1 : Create X values 

In [ ]:

x1 = np.linspace(-100, 100, 100)# linspace(start, stop, num) generates equally spaced numbers.

print(x1)

### Step 2 : Compute y 

In [7]:
y = 2*x1 + 3

### Step 3 : Plot function 

In [ ]:
plt.plot(x1, y)

plt.title("y = 2x + 3")
plt.xlabel("x")
plt.ylabel("y")

plt.grid()
plt.show()

## Exercise 3 : Quadratic equation 
Equation : y=2x^2+3x+4

### Step 1 : Create x values 

In [9]:
x1 = np.linspace(-10, 10, 100) 

### Step 2 : Compute y 

In [10]:
y = 2*x1**2 + 3*x1 + 4

### Step 3 : Plot function 

In [ ]:
plt.plot(x1, y)

plt.title("y = 2x² + 3x + 4")
plt.xlabel("x")
plt.ylabel("y")

plt.grid()
plt.show()

## Exercise 4 : Gaussian PDF 
### Step 1 : Create x values initialize mean and standard deviation 

In [ ]:
mean = 0
sigma = 15

x = np.linspace(-100, 100, 100)

### Step 2 : Compute the PDF equation 

In [ ]:
pdf = (1/np.sqrt(2*np.pi))*np.exp(-(x**2)/2) # np.exp() = means e power x 

### Step 3 : Plot 

In [ ]:
# Gaussian PDF formula
plt.plot(x, pdf)
plt.xlabel("x")
plt.ylabel("Gaussian PDF")
plt.title("Gaussian PDF (mean=0, sigma=15)")
plt.grid(True)
plt.show()

## Exercise 5 : Derivatives 
### Step 1 : Create x values 

In [17]:
x1=np.linspace(-10,10,100)

### Step 2 : Compute equation 

In [18]:
y=x1**2

### Step 3 : Plot 

In [ ]:
plt.plot(x1,y)
plt.xlabel("x1")
plt.ylabel("y")
plt.title("y = x1^2")
plt.grid(True)
plt.show()

### Step 4 : Innitialize array of points at which derivatives have to be taken 

In [20]:
dx=np.array([-5,-3,0,3,5])


### Step 5 : take dervatives and print 

In [21]:
derivatives = 2 * dx

print("Derivatives:", derivatives)

Derivatives: [-10  -6   0   6  10]


## Exercise 6 : Multivariable Function 
### Step 1 : Choose values for x 

In [22]:
x1 = 1
x2 = 2
x3 = 3

### Step 2 : compute the equation 

In [23]:
y = 2*x1 + 3*x2 + 3*x3 + 4

print(y)

21


### Step 3 : Gradient 

In [24]:
gradient = np.array([2, 3, 3])

print(gradient)

[2 3 3]


## Exercise 7 : Linear Model 

In [ ]:
# Coefficients represented as 'theta'
theta = np.array([
    [2],
    [3],
    [3]
])

In [ ]:
# 5 samples reprsented as matrix X 
X = np.array([
    [1,0,2],
    [0,1,1],
    [2,1,0],
    [1,1,1],
    [0,2,1]
])

In [27]:
y = X @ theta

print(y)

[[8]
 [6]
 [7]
 [8]
 [9]]
